context:
  version: "0.0.15.a3"

package:
  name: khiops-driver-gcs
  version: ${{ version }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-gcs/archive/refs/tags/${{ version }}.tar.gz
  sha256: 6b2a8339f3b2eed28de015f7e5a5a86ce34afec1885ef0649b1bd0342d147a81

build:
  number: 3

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - fmt
    - spdlog
    - zlib
    - libgoogle-cloud-storage-devel
    - libboost-devel
    - libboost-headers
    - libcrc32c
    - if: win
      then: libcurl

tests:
  - script:
    - if: unix
      then: test -f $PREFIX/lib/libkhiopsdriver_file_gcs${SHLIB_EXT}
      else: 
        - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_gcs.dll exit 1 

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Google Cloud Storage
  description: The GCS driver plugin extends Khiops to enable processing of data files located on Google Cloud Storage

extra:
  recipe-maintainers:
    - popescu-v
    - sgouache
